In [1]:
# Dependencies
import pandas as pd
from bs4 import BeautifulSoup as bs
import requests
from splinter import Browser

In [2]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/'

In [3]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data1 =[]

for name in names: 
    data1.append(name.get_text())

In [4]:
data1

['A & T Pancake House and Grill7036 North Clark Street Chicago IL 60626773-274-0036',
 'Adobo Grill215 W North Ave Chicago IL 60610312-366-2150',
 "Arturo's Mexican Restaurant7151 S Western Ave Chicago IL 60636773-776-0433",
 'Atolito4429 N Broadway St Chicago IL 60640773-334-7711',
 'Atolito Mexican Kitchen4429 N Broadway St Chicago IL 60640773-334-7711',
 'Atolito Mexican Kitchen2436 N Lincoln Ave Chicago IL 60614773-880-6666',
 'Azteca7531 N Wolcott Ave Chicago IL 60626773-973-3570',
 'Azteca Grill3731 North Clark Street Chicago IL 60613773-857-6565',
 'Baja Fresh Mexican Grill180 N Michigan Ave Ste 104 Chicago IL 60601312-223-8590',
 'Buenos Tacos283 N Pulaski Rd Chicago IL 60624773-826-1988',
 'Burrito Beach210 S Canal St Chicago IL 60606312-575-9749',
 'Burrito Beach5600 Mannheim Rd Chicago IL 60666773-462-0190',
 'Burrito Beach200 E Ohio St Chicago IL 60611312-335-0668',
 'Burrito Beach19 S LaSalle St Chicago IL 60603312-578-9340',
 'Burrito Beach233 N Michigan Ave Chicago IL 60601312-861-1986',
 'Burrito Beach500 W Madison St Chicago IL 60661312-466-1828',
 'Burrito Beach251 E Huron St Chicago IL 60611312-475-0442',
 'Burrito Buggy206 W Van Buren St Chicago IL 60607312-362-0199',
 'Burrito Buggy On117 S Clinton St Chicago IL 60661312-258-9158',
 'Burrito Grande5108 S Archer Ave Chicago IL 60632773-581-8898',
 'Burrito House3145 W Addison St Chicago IL 60618773-279-9111']

In [5]:
##############################################################################
########### Compile Data

In [6]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+2/'

In [7]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data2 =[]

for name in names: 
    data2.append(name.get_text())

In [8]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+3/'

In [9]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data3 =[]

for name in names: 
    data3.append(name.get_text())

In [10]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+4/'

In [11]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data4 =[]

for name in names: 
    data4.append(name.get_text())

In [12]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+5/'

In [13]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data5 =[]

for name in names: 
    data5.append(name.get_text())

In [14]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+6/'

In [15]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data6 =[]

for name in names: 
    data6.append(name.get_text())

In [16]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+7/'

In [17]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data7 =[]

for name in names: 
    data7.append(name.get_text())

In [18]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+8/'

In [19]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data8 =[]

for name in names: 
    data8.append(name.get_text())

In [20]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+9/'

In [21]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data9 =[]

for name in names: 
    data9.append(name.get_text())

In [22]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+10/'

In [23]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data10 =[]

for name in names: 
    data10.append(name.get_text())

In [24]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+11/'

In [25]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data11 =[]

for name in names: 
    data11.append(name.get_text())

In [26]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+12/'

In [27]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data12 =[]

for name in names: 
    data12.append(name.get_text())

In [28]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+13/'

In [29]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data13 =[]

for name in names: 
    data13.append(name.get_text())

In [30]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+14/'

In [31]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data14 =[]

for name in names: 
    data14.append(name.get_text())

In [32]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+15/'

In [33]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data15 =[]

for name in names: 
    data15.append(name.get_text())

In [34]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+16/'

In [35]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data16 =[]

for name in names: 
    data16.append(name.get_text())

In [36]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+17/'

In [37]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data17 =[]

for name in names: 
    data17.append(name.get_text())

In [38]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+18/'

In [39]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data18 =[]

for name in names: 
    data18.append(name.get_text())

In [40]:
# URL of page to be scraped
url = 'http://www.yellowpagecity.com/US/IL/Chicago/Mexican+Restaurants/Page+19/'

In [41]:
response = requests.get(url)
soup = bs(response.text, 'html.parser')
names = soup.find_all('a', class_= "listing-wrap")
data19 =[]

for name in names: 
    data19.append(name.get_text())

In [42]:
#################################################################################################
## Finalize Dataframe

In [43]:
master_data = data1+data2+data3+data4+data5+data6+data7+data8+data9+data10+data11+data12+data13+data14+data15+data16+data17+data18+data19
# master_data
mexican_df = pd.DataFrame({'Name': master_data})
# pizza_df.head(10)
mexican2_df = mexican_df.drop(mexican_df.index[0])

mexican2_df.head(10)

                                                 Name
1   Adobo Grill215 W North Ave Chicago IL 60610312...
2   Arturo's Mexican Restaurant7151 S Western Ave ...
3   Atolito4429 N Broadway St Chicago IL 60640773-...
4   Atolito Mexican Kitchen4429 N Broadway St Chic...
5   Atolito Mexican Kitchen2436 N Lincoln Ave Chic...
6   Azteca7531 N Wolcott Ave Chicago IL 60626773-9...
7   Azteca Grill3731 North Clark Street Chicago IL...
8   Baja Fresh Mexican Grill180 N Michigan Ave Ste...
9   Buenos Tacos283 N Pulaski Rd Chicago IL 606247...
10  Burrito Beach210 S Canal St Chicago IL 6060631...

In [ ]:
##################################################################################
############################### Clean the data ###################################

In [44]:
##Extract the ZipCode and Telephone Number info from the mexican2_df["Name"] column 
new = mexican2_df["Name"].str.split("IL",n=1,expand = True)

# making separate "ziptel" column from new data frame 
mexican2_df["name2"]= new[0] 
mexican2_df["ziptel"]=new[1]

mexican2_df.drop(columns = ["Name"], inplace = True)

mexican2_df['Phone Number'] = mexican2_df['ziptel'].str[-12:]
# print(pizza2_df['Phone Number'])
mexican2_df['Zip Code'] = mexican2_df['ziptel'].str[:6]
# print(pizza2_df['Zip Code'])
mexican2_df.drop(columns =["ziptel"], inplace = True)

In [45]:
mexican2_df.head(10)

                                                name2  Phone Number Zip Code
1                 Adobo Grill215 W North Ave Chicago   312-366-2150    60610
2   Arturo's Mexican Restaurant7151 S Western Ave ...  773-776-0433    60636
3                  Atolito4429 N Broadway St Chicago   773-334-7711    60640
4   Atolito Mexican Kitchen4429 N Broadway St Chic...  773-334-7711    60640
5   Atolito Mexican Kitchen2436 N Lincoln Ave Chic...  773-880-6666    60614
6                   Azteca7531 N Wolcott Ave Chicago   773-973-3570    60626
7        Azteca Grill3731 North Clark Street Chicago   773-857-6565    60613
8   Baja Fresh Mexican Grill180 N Michigan Ave Ste...  312-223-8590    60601
9               Buenos Tacos283 N Pulaski Rd Chicago   773-826-1988    60624
10               Burrito Beach210 S Canal St Chicago   312-575-9749    60606

In [46]:
##Extract the City and Telephone Number info from the mexican2_df["Name"] column 
new = mexican2_df["name2"].str.split("Chicago",n=1,expand = True)

# making separate "name3" column from new data frame 
mexican2_df["name3"]= new[0] 
mexican2_df["chicago"]= new[1]

mexican2_df.drop(columns = ["name2"], inplace = True)
mexican2_df.drop(columns = ["chicago"], inplace = True)

#Choose the most important columns for the next part of the ETL Project
mexican2_df = mexican2_df[["name3","Phone Number","Zip Code"]]
mexican2_df.head(10)

                                                name3  Phone Number Zip Code
1                         Adobo Grill215 W North Ave   312-366-2150    60610
2      Arturo's Mexican Restaurant7151 S Western Ave   773-776-0433    60636
3                          Atolito4429 N Broadway St   773-334-7711    60640
4          Atolito Mexican Kitchen4429 N Broadway St   773-334-7711    60640
5          Atolito Mexican Kitchen2436 N Lincoln Ave   773-880-6666    60614
6                           Azteca7531 N Wolcott Ave   773-973-3570    60626
7                Azteca Grill3731 North Clark Street   773-857-6565    60613
8   Baja Fresh Mexican Grill180 N Michigan Ave Ste...  312-223-8590    60601
9                       Buenos Tacos283 N Pulaski Rd   773-826-1988    60624
10                       Burrito Beach210 S Canal St   312-575-9749    60606

In [48]:
mexican2_df.to_excel('../../Desktop/export_dataframe.xlsx', index = None, header=True) #Don't forget to add '.xlsx' at the end of the path

In [49]:
mexican3_df = pd.read_csv("../../Desktop/mexicanData.csv")

In [50]:
mexican3_df.head()

                                             name3  Phone Number  Zip Code
0                     Adobo Grill,215 W North Ave   312-366-2150     60610
1  Arturo's Mexican Restaurant,7151 S Western Ave   773-776-0433     60636
2                      Atolito,4429 N Broadway St   773-334-7711     60640
3      Atolito Mexican Kitchen,4429 N Broadway St   773-334-7711     60640
4      Atolito Mexican Kitchen,2436 N Lincoln Ave   773-880-6666     60614

In [51]:
##Extract and separate "Name" and "Address" from the mexican3_df["name3"] column

# dropping null value columns to avoid errors 
mexican3_df.dropna(inplace = True) 
  
# new dataframe with split value columns 
new = mexican3_df["name3"].str.split(",", n = 1, expand = True) 
  
# making separate "Name" column from new data frame 
mexican3_df["Name"]= new[0] 
  
# making separate "Address" column from new data frame 
mexican3_df["Address"]= new[1] 

# Dropping old "name3" column
mexican3_df.drop(columns =["name3"], inplace = True) 

mexican3_df.head()

   Phone Number  Zip Code                         Name              Address
0  312-366-2150     60610                  Adobo Grill     215 W North Ave
1  773-776-0433     60636  Arturo's Mexican Restaurant  7151 S Western Ave
2  773-334-7711     60640                      Atolito  4429 N Broadway St
3  773-334-7711     60640      Atolito Mexican Kitchen  4429 N Broadway St
4  773-880-6666     60614      Atolito Mexican Kitchen  2436 N Lincoln Ave

In [52]:
#Choose the most important columns for the next part of the ETL Project
mexicanFinal_df = mexican3_df[["Name","Address","Phone Number","Zip Code"]]
#Rename column names so that they are SQL feiendly
mexicanFinal_df.columns=["Name","Address","Phone_Number","Zip_Code"]
mexicanFinal_df.head()
mexicanFinal_df.reset_index(drop = True)

,Name,Address,Phone_Number,Zip_Code
0,Adobo Grill,215 W North Ave,312-366-2150,60610
1,Arturo's Mexican Restaurant,7151 S Western Ave,773-776-0433,60636
2,Atolito,4429 N Broadway St,773-334-7711,60640
3,Atolito Mexican Kitchen,4429 N Broadway St,773-334-7711,60640
4,Atolito Mexican Kitchen,2436 N Lincoln Ave,773-880-6666,60614
5,Azteca,7531 N Wolcott Ave,773-973-3570,60626
6,Azteca Grill,3731 North Clark Street,773-857-6565,60613
7,Baja Fresh Mexican Grill,180 N Michigan Ave Ste 104,312-223-8590,60601
8,Buenos Tacos,283 N Pulaski Rd,773-826-1988,60624
9,Burrito Beach,210 S Canal St,312-575-9749,60606
10,Burrito Beach,5600 Mannheim Rd,773-462-0190,60666
11,Burrito Beach,200 E Ohio St,312-335-0668,60611
12,Burrito Beach,19 S LaSalle St,312-578-9340,60603
13,Burrito Beach,233 N Michigan Ave,312-861-1986,60601
14,Burrito Beach,500 W Madison St,312-466-1828,60661
15,Burrito Beach,251 E Huron St,312-475-0442,60611
16,Burrito Buggy,206 W Van Buren St,312-362-0199,60607
17,Burrito Buggy,117 S Clinton St,312-258-9158,60661
18,Burrito Grande,5108 S Archer Ave,773-581-8898,60632
19,Burrito House,3145 W Addison St,773-279-9111,60618
20,Burrito King,4754 W Belmont Ave,773-280-9251,60641
21,C Manny's Mexican Restaurant,3641 W Irving Park Rd,773-583-1590,60618
22,Cabos Baja Cafe & Mexican Grill,5750 North California Avenue,872-208-5842,60659
23,Cafe Rio,3222 W Bryn Mawr Ave,773-942-6169,60659
24,Calis Mexican American Grill Menrcan,2333 S Michigan Ave,312-794-5418,60616
25,Cantina Laredo,508 N State St,312-955-0014,60654
26,Carbon Live Fire Mexican Grill,810 N Marshfield Ave,312-733-0978,60622
27,Carniceria Y Taqueria Guerro,1856 N Richmond St,773-252-0906,60647
28,Carnitas Michoacan,4235 W 63rd St,773-912-6607,60629
29,Carnitas Uruapan,1725 W. 18th St.,312-226-2654,60608
...,...,...,...,...
390,Taqueria Los Comales,1544 W 18th St,312-666-2251,60608
391,Taqueria Los Comales,3141 W 26th St,773-523-1689,60623
392,Taqueria Los Comales,6035 S Pulaski Rd,773-838-1977,60629
393,Taqueria Los Gallo,4211 W 26th St,773-762-7452,60623
394,Taqueria Los Gallo,6220 S Archer Ave,773-585-8835,60638
395,Taqueria Los Gavilanes,2147 S California Ave,773-376-3455,60608
396,Taqueria Mano A Mano,3036 N Pulaski Rd,773-736-1617,60641
397,Taqueria Miguadalupe,7021 N Clark St,773-338-8644,60626
398,Taqueria Morelia,3943 W Lawrence Ave,773-509-1727,60625
399,Taqueria Ochoa,4151 W 47th St,773-376-5330,60632
400,Taqueria Sacramento,10148 S Ewing Ave,773-221-9440,60617
401,Taqueria San Juanito,4714 N Kedzie Ave,773-583-0304,60625
402,Taqueria Valparaiso,10500 S Western Ave,773-238-3982,60643
403,Tecalitlan Restaurant,1814 W Chicago,773-384-4285,60622
404,Thai & Burrito,2439 N Clark St,773-549-5329,60614
405,Tio Luis Tacos,3856 South Archer Avenue,773-843-0098,60632
406,Tiztal Café,4631 North Clark Street,773-271-4631,60640
407,Tolotzin Mexican Restaurant N Restaura,4411 N Broadway St,773-944-4300,60640
408,Tom Tom Tamale & Bakery Co,4750 S Washtenaw Ave,773-523-5675,60632
409,Tono Tacos,6102 W Diversey Ave,773-887-5814,60639
410,Tony's Tacos,3508 W 63rd St,773-424-0056,60629
411,Towns Limits Cantina,1838 W Lawrence Ave,773-989-6894,60640
412,Uncle Julio's,855 W North Ave,312-266-4222,60642
413,Uncle Julios Fine Mexican Food,855 W North Ave,312-266-4222,60642
414,Viva Mexico,3115 W 26th St,773-376-4967,60623
415,Xoco,449 N Clark St,312-334-3688,60654
416,Xocome Antojeria,5200 South Archer Avenue,773-498-6679,60632
417,Yolis Tacos,2640 W Chicago,872-802-4544,60622
418,Zapatista,444 W Fullerton Pkwy,773-525-4100,60614
419,Zemba Mexican Grill,605 W Lake St,312-234-9900,60661

In [53]:
mexicanFinal_df.to_excel('../../Desktop/export_dataframe2.xlsx', index = None, header=True) #Don't forget to add '.xlsx' at the end of the path